# Generated by Django 5.0.4 on 2024-04-18 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcement_api", "0002_ad_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="data",
            new_name="created_at",
        ),
    ]
